# Generated by Django 4.1.2 on 2022-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
